version: '3'
services:
    app:
        environment:            
            - DB_NAME=email_sender
            - DB_PASS=1234
            - DB_USER=postgres
            - DB_HOST=db
            - REDIS_HOST=queue